# Build
custom_build(
   # Name of the target
   ref = 'dispatcher-service',
   # Command to build image
   command = './gradlew bootBuildImage --imageName $EXPECTED_REF',
   # List of files to watch for changes
   deps = ['build.gradle', 'src']
)

# Deploy
k8s_yaml(['k8s/deployment.yaml', 'k8s/service.yaml'])

# Manage
k8s_resource('dispatcher-service', port_forwards=['9003'])