### GET Home
GET http://localhost:9001/

### GET Books
GET http://localhost:9001/books

### POST
POST http://localhost:9001/books
Content-Type: application/json

{
  "isbn": {{isbn}},
  "title": "Northern Lights",
  "author": "Lyra Silverstar",
  "price": 9.90,
  "publisher": "Penguin Books"
}

### GET
GET http://localhost:9001/books/1234567891
Accept: application/json


### Config Server
http://localhost:8888/catalog-service/default

### Order Service
### POST Order
POST http://localhost:9002/orders
Content-Type: application/json

{
  "isbn": {{isbn}},
  "quantity": 3
}

### GET Orders
GET http://localhost:9002/orders