# Build
custom_build(
   # Name of the target
   ref = 'catalog-service',
   # Command to build image
   command = './gradlew bootBuildImage --imageName $EXPECTED_REF',
   # List of files to watch for changes
   deps = ['build.gradle', 'src']
)

# Deploy
#k8s_yaml(['k8s/deployment.yaml', 'k8s/service.yaml'])
k8s_yaml(kustomize('k8s'))

# Manage
k8s_resource('catalog-service', port_forwards=['9001'])