version: "3.8"
networks:
  polar:
    driver: bridge
services:
  # Servers
  polar-postgres:
    image: "postgres:14.4"
    container_name: "polar-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d polardb_catalog -U user" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - polar
  polar-redis:
    image: "redis:7.0"
    container_name: "polar-redis"
    ports:
      - 6379:6379
    networks:
      - polar
  polar-rabbitmq:
    image: "rabbitmq:3.10-management"
    container_name: "polar-rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmqctl status" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - polar
  polar-keycloak:
    image: quay.io/keycloak/keycloak:19.0
    container_name: "polar-keycloak"
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - 8080:8080
    networks:
      - polar
  polar-ui:
    image: "ghcr.io/polarbookshop/polar-ui:v1"
    container_name: "polar-ui"
    ports:
      - 9004:9004
    environment:
      - PORT=9004
    networks:
      - polar
  ## Applications
  config-service:
    depends_on:
      polar-postgres:
        condition: service_healthy
    image: "config-service"
    container_name: "config-service"
    ports:
      - 8888:8888
    environment:
      - BPL_JVM_THREAD_COUNT=50
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8888' || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - polar
  catalog-service:
    depends_on:
      polar-postgres:
        condition: service_healthy
      config-service:
        condition: service_healthy
    image: "catalog-service"
    container_name: "catalog_service"
    ports:
      - 9001:9001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - SPRING_PROFILES_ACTIVE=testData
      - SPRING_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://polar-keycloak:8080/realms/PolarBookshop
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/9001' || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - polar
  order-service:
    depends_on:
      polar-postgres:
        condition: service_healthy
      config-service:
        condition: service_healthy
      catalog-service:
        condition: service_healthy
    image: "order-service"
    container_name: "order_service"
    ports:
      - 9002:9002
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_FLYWAY_URL=jdbc:postgresql://polar-postgres:5432/polardb_order
      - SPRING_R2DBC_URL=r2dbc:postgresql://polar-postgres:5432/polardb_order
      - SPRING_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://polar-keycloak:8080/realms/PolarBookshop
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/9002' || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - polar
  edge-service:
    depends_on:
      - polar-keycloak
      - polar-redis
      - polar-ui
    image: "edge-service"
    container_name: "edge-service"
    ports:
      - 9000:9000
      - 8000:8000
    environment:
      # Buildpacks environment variable to enable debug through a socket on port 8000
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8000
      - CATALOG_SERVICE_URL=http://catalog-service:9001
      - ORDER_SERVICE_URL=http://order-service:9002
      - SPA_URL=http://polar-ui:9004
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_REDIS_HOST=polar-redis
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://host.docker.internal:8080/realms/PolarBookshop
